# Generated by Django 2.2.2 on 2019-06-12 19:09

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=127, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=127, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, default=None, error_messages={'unique': 'A user with that email id already exists.'}, help_text='Required. A valid email address.', max_length=254, null=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='A Valid phone number', max_length=128, region=None)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('regular', 'Regular')], default='regular', max_length=127, verbose_name='Role')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
